version: '3.5'

services:
  miniflux-db:
    image: postgres:13-alpine
    container_name: miniflux-db
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - miniflux-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=${MINIFLUX_DB_PASS}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
    labels:
      - diun.enable=true

  miniflux-app:
    image: miniflux/miniflux:latest
    container_name: miniflux-app
    restart: unless-stopped
    depends_on:
      miniflux-db:
        condition: service_healthy
    networks:
      default:
      traefik_proxy:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - BASE_URL=https://${MINIFLUX_URL}
      - DATABASE_URL=host=miniflux-db user=miniflux password=${MINIFLUX_DB_PASS} dbname=miniflux sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=0
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
    healthcheck:
      test: ["CMD", "/usr/bin/miniflux", "-healthcheck", "auto"]
    labels:
      - diun.enable=true
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      - traefik.http.middlewares.miniflux-https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.miniflux-https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.miniflux-http.rule=Host(`${MINIFLUX_URL}`)
      - traefik.http.routers.miniflux-http.entrypoints=http
      - traefik.http.routers.miniflux-http.middlewares=miniflux-https-redirect
      - traefik.http.routers.miniflux-http.service=miniflux
      - traefik.http.routers.miniflux-https.rule=Host(`${MINIFLUX_URL}`)
      - traefik.http.routers.miniflux-https.entrypoints=https
      - traefik.http.routers.miniflux-https.middlewares=secHeaders@file
      - traefik.http.routers.miniflux-https.tls=true
      - traefik.http.routers.miniflux-https.service=miniflux
      - traefik.http.services.miniflux.loadbalancer.server.port=8080

volumes:
  miniflux-db:

networks:
  traefik_proxy:
    external: true
  default:
    ipam:
      config:
        - subnet: 172.16.3.0/24
