version: '3.5'

services:
  bookstack-db:
    image: mariadb:latest
    container_name: bookstack-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - bookstack-db:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASS}
      - MARIADB_DATABASE=bookstack
      - MARIADB_USER=bookstack
      - MARIADB_PASSWORD=${BOOKSTACK_DB_PASS}
      - MARIADB_INITDB_SKIP_TZINFO=1
    labels:
      - diun.enable=true

  bookstack-app:
    image: ghcr.io/linuxserver/bookstack:latest
    container_name: bookstack-app
    restart: unless-stopped
    depends_on:
      - bookstack-db
    networks:
      default:
      traefik_proxy:
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /opt/portainer/data/bookstack:/config
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://${BOOKSTACK_URL}
      - DB_HOST=bookstack-db
      - DB_DATABASE=bookstack
      - DB_USER=bookstack
      - DB_PASS=${BOOKSTACK_DB_PASS}
    labels:
      - diun.enable=true
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      - traefik.http.middlewares.bookstack-app-https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.bookstack-app-https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.bookstack-app-http.rule=Host(`${BOOKSTACK_URL}`)
      - traefik.http.routers.bookstack-app-http.entrypoints=http
      - traefik.http.routers.bookstack-app-http.middlewares=bookstack-app-https-redirect
      - traefik.http.routers.bookstack-app-http.service=bookstack-app
      - traefik.http.routers.bookstack-app-https.rule=Host(`${BOOKSTACK_URL}`)
      - traefik.http.routers.bookstack-app-https.entrypoints=https
      - traefik.http.routers.bookstack-app-https.middlewares=secHeaders@file
      - traefik.http.routers.bookstack-app-https.tls=true
      - traefik.http.routers.bookstack-app-https.service=bookstack-app
      - traefik.http.services.bookstack-app.loadbalancer.server.port=80

volumes:
  bookstack-db:

networks:
  traefik_proxy:
    external: true
  default:
    ipam:
      config:
        - subnet: 172.16.5.0/24
